//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobWorks = new HashSet<JobWork>();
        }
    
        public int Id { get; set; }
        public string JobNumber { get; set; }
        public Nullable<System.DateTime> Arrival_Time { get; set; }
        public int Client_Id { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public string Status { get; set; }
        public string JobLevel { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string JobType { get; set; }
        public string UploadedBy { get; set; }
        public string ClientFilePath { get; set; }
        public string MaxFilePath { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWork> JobWorks { get; set; }
    }
}
