//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobWork
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public int Client_Id { get; set; }
        public string JobWorkLevel { get; set; }
        public string LevelStatus { get; set; }
        public Nullable<System.DateTime> DownloadTime { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
