//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaf
    {
        public int Id { get; set; }
        public int CasualLeaves { get; set; }
        public int PrivilegeLeaves { get; set; }
        public int SpecialLeaves { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
