//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxMRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRecord
    {
        public int Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int NoOfDays { get; set; }
        public string LeaveType { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReviewDate1 { get; set; }
        public Nullable<System.DateTime> ReviewDate2 { get; set; }
        public string ReviewStatus1 { get; set; }
        public string ReviewStatus2 { get; set; }
        public string ReviewComments { get; set; }
        public string FinalStatus { get; set; }
        public int Employee_Id { get; set; }
        public int Reviewer1_Id { get; set; }
        public Nullable<int> Reviewer2_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
    }
}
